version: '3.5'

services:
  redis:
    container_name: redis
    image: redis
    hostname: redis
    privileged: true
    ports:
      - '6379:6379'
    network_mode: host

  database:
    env_file:
      - .env
    build: database
    container_name: dataservice
    privileged: true
    hostname: worker
    volumes:
      - ./cache/db:/db
    depends_on:
      - redis
    network_mode: host


  btc_worker:
    #network_mode: "host"
    env_file:
      - .env
    build: btc
    container_name: btc_worker
    privileged: true
    hostname: btc_worker
    depends_on:
      - redis
    network_mode: host


  telegram_bot:
    env_file:
      - .env
    build: telegram
    container_name: telegram_bot
    privileged: true
    hostname: telegram_bot
    depends_on:
      - redis
    network_mode: host

#  discord_bot:
#    env_file:
#      - .env
#    build: discord
#    container_name: discord_bot
#    privileged: true
#    hostname: discord_bot
#
#    depends_on:
#      - redis
networks:
 default:
  name: gate-lottery-bot
