version: '3.5'

services:
  redis:
    #network_mode: "host"
    container_name: redis
    image: redis
    hostname: redis
    privileged: true
    ports:
      - '6379:6379'

  database:
    #network_mode: "host"
    env_file:
      - .env
    build: database
    container_name: dataservice
    privileged: true
    hostname: worker
    volumes:
      - ./cache/db:/db
    depends_on:
      - redis

  btc_worker:
    #network_mode: "host"
    env_file:
      - .env
    build: btc
    container_name: btc_worker
    privileged: true
    hostname: btc_worker
    depends_on:
      - redis

  telegram_bot:
    env_file:
      - .env
    #network_mode: "host"
    build: telegram
    container_name: telegram_bot
    privileged: true
    hostname: telegram_bot

    depends_on:
      - redis
networks:
 default:
  name: gate-bot
