swagger: "2.0"
info:
  title: Data Service API
  description: Lottery bot Data Service which stores Users info, Lotteries and Bets.
  license:
    name: APLv2
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
basePath: /api
paths:
    /users:
      get:
        operationId: api.get_users
        description: Returns an information about users registered in the service
        produces:
          - application/json
        parameters:
          - in: query
            name: id
            type: integer
            required: true
        responses:
          '200':
            description: List of user data objects
            schema:
              type: array
              items:
                type: string
          '400':
            description: Generic error
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "User is not found in the database"
      post:
        operationId: api.post_users
        description: Registers new user
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - name: body
            in: body
            required: true
            schema:
              # Body schema with atomic property examples
              type: object
              properties:
                id:
                  type: integer
                  example: 0
        responses:
          '201':
            description: Created
