swagger: "2.0"
info:
  title: Data Service API
  description: Lottery bot Data Service which stores Users info, Lotteries and Bets.
  license:
    name: APLv2
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
basePath: /api
paths:
    /users:
      get:
        operationId: api.get_user
        description: Returns an information about users registered in the service
        produces:
          - application/json
        parameters:
          - in: query
            name: id
            type: integer
            required: true
        responses:
          '200':
            description: List of user data objects
            schema:
              type: array
              items:
                type: string
          '400':
            description: Generic error
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "User is not found in the database"
      post:
        operationId: api.post_user
        description: Registers new user
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - name: body
            in: body
            required: true
            schema:
              # Body schema with atomic property examples
              type: object
              required:
                - id
                - alias
                - firstName
                - lastName
              properties:
                id:
                  type: integer
                  example: 0
                alias:
                  type: string
                  example: "ur dad"
                firstName:
                  type: string
                  example: "haha"
                lastName:
                  type: string
                  example: "haha"

        responses:
          '201':
            description: Created

    /users/allUsers:
      get:
        operationId: api.get_users
        description: Returns an information about all users registered in the service
        produces:
          - application/json
        responses:
          '200':
            description: List of user data objects
            schema:
              type: array
              items:
                type: string
          '400':
            description: Generic error
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "User is not found in the database"

    /users/vote:
      get:
        operationId: api.get_user_vote
        description: Returns an information about user vote registered in the service
        produces:
          - application/json
        parameters:
          - in: query
            name: id
            type: integer
            required: true
        responses:
          '200':
            description: List of user data objects
            schema:
              type: array
              items:
                type: string
          '400':
            description: Generic error
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "User is not found in the database"
      post:
        operationId: api.post_user_vote
        description: Registers new bet
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - name: body
            in: body
            required: true
            schema:
              # Body schema with atomic property examples
              type: object
              required:
                - idUser
                - idLottery
                - userBet
              properties:
                idUser:
                  type: integer
                  example: 0
                idLottery:
                  type: integer
                  example: 99
                userBet:
                  type: string
                  example: "banana"

        responses:
          '201':
            description: Created

    /users/allVote:
      get:
        operationId: api.get_users_vote
        description: Returns an information about all user vote registered in the service
        produces:
          - application/json
        responses:
          '200':
            description: List of user data objects
            schema:
              type: array
              items:
                type: string
          '400':
            description: Generic error
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "Users not found in the database"

    /lottery:
      get:
        operationId: api.get_lottery
        description: Returns an information about a lottery registered in the service
        produces:
          - application/json
        parameters:
          - in: query
            name: id
            type: integer
            required: true
        responses:
          '200':
            description: A lottery data objects
            schema:
              type: array
              items:
                type: string
          '400':
            description: Generic error
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "Lottery is not found in the database"
      post:
        operationId: api.start_lottery
        description: Registers a new lottery
        consumes:
          - application/json
        produces:
          - application/json
        responses:
          '201':
            description: Created

    /lottery/timeLeft:
      get:
        operationId: api.get_time_left
        description: Returns an information about a lottery registered in the service
        produces:
          - application/json
        parameters:
          - in: query
            name: idLottery
            type: integer
            required: true
        responses:
          '200':
            description: returned Time left on a lottery
          '400':
            description: Generic error
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "Lottery is not found in the database"

    /lottery/height:
      get:
        operationId: api.get_height
        description: Returns an information about a lottery's height registered in the service
        produces:
          - application/json
        responses:
          '200':
            description: returned a lottery starting block height
          '400':
            description: Generic error
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "Lottery is not found in the database"

    /lottery/winningFruit:
      get:
        operationId: api.get_winning_fruit
        description: Returns the winning fruit of a lottery
        produces:
          - application/json
        parameters:
          - in: query
            name: idLottery
            type: integer
            required: true
        responses:
          '200':
            description: winning fruit of a lottery
            schema:
              type: array
              items:
                type: string
          '400':
            description: Generic error
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "Lottery is not found in the database"
      post:
        operationId: api.post_winning_choice
        description: post a winning choice to a lottery database
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - name: body
            in: body
            required: true
            schema:
              # Body schema with atomic property examples
              type: object
              required:
                - winningChoice
              properties:
                winningChoice:
                  type: integer
                  example: 0
        responses:
          '201':
            description: post the winning choice

    /lottery/running:
      get:
        operationId: api.get_running_lottery
        description: Returns an id of a running lottery
        produces:
          - application/json
        responses:
          '200':
            description: returned id lottery
          '400':
            description: Generic error
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "No lottery is running"


    /lottery/winners:
      get:
        operationId: api.get_winners
        description: Returns the winners of a lottery
        produces:
          - application/json
        parameters:
          - in: query
            name: idLottery
            type: integer
            required: true
        responses:
          '200':
            description: winner of a lottery
            schema:
              type: array
              items:
                type: string
          '400':
            description: Generic error
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "Lottery is not found in the database"

    /lottery/stop:
      post:
        operationId: api.stop_lottery
        description: Stop a running lottery
        consumes:
          - application/json
        produces:
          - application/json
        responses:
          '201':
            description: Created


